---
title: "`r knitr::current_input()`"
date: "`r paste('last updated', 
    format(lubridate::now(), ' %d %B %Y'))`"
output:   
  html_document:  
        code_folding: show
        toc: true 
        toc_depth: 2
        toc_float: true
        mathjax: default
  pdf_document:   
    latex_engine: xelatex  
    toc: true
    toc_depth:  2   
fontsize: 11pt   
geometry: margin=0.4in,top=0.25in   
---
### MY NOTES, for Distill

```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,
                      comment = "      ##",
                      error = TRUE,
                      collapse = FALSE   ) # easier to read
```


```{r eval=F, include = F}

{
  library(distill)
  library(rmarkdown)
}

## 
{
  getwd()
  site_generator()
  x  <- site_config()
  x$output_dir
  x$repository_url
}



## clean
{
  clean_site()
  rmarkdown::clean_site(preview = F)
}


# =================
##          FIRST
# =================

## individual (puts file in blog5/docs/posts/....)
## ~/code/blog5/_posts/
  rmarkdown::render("~/code/blog5/_posts/welcome/welcome.Rmd")


  # used copy & paste of files
  rmarkdown::render("~/code/blog5/_posts/R_setup_environment/R_setup_environment.Rmd")
  rmarkdown::render("~/code/blog5/_posts/random-R-notes/useful_base_R.Rmd")

  rmarkdown::render("~/code/blog5/_posts/reading_list/reading_list.Rmd")
  rmarkdown::render("~/code/blog5/_posts/people_list/people_I_follow.Rmd")

  rmarkdown::render("~/code/blog5/_posts/environ/0000_ls_objects.Rmd")
  rmarkdown::render("~/code/blog5/_posts/publish_project/latex_trees.Rmd")
  rmarkdown::render("~/code/blog5/_posts/watch/watch.Rmd")

  # slow, if big file
  ## Given a html file, still must create a stub Rmd file, process (same as Welcome)
  rmarkdown::render("~/code/blog5/_posts/bookmark_list/bookmarks.Rmd")



  

# ==================
##          SECOND
# ==================
    
### This one works...
  rmarkdown::render_site("~/code/blog5/index.Rmd")




## new post
  distill::create_post(title="post_TWO")

  distill::create_post(title= "snippet_05",
  collecton = "_snippets",
  author = "jim",
  slug = "_snippets",
  edit = F
  )

# new blog (run from /code)
  distill::create_blog(dir=".", title="blog5")
```

